site_name: NonSenseGenerator
theme: readthedocs
repo_url: https://github.com/liamtoaldo/NonSenseGenerator
repo_name: NonSenseGenerator
edit_uri: edit/main/docs/mkdocs/NonSenseGenerator/docs/
site_description: A tool to generate nonsensical text based on user input.
site_author: 4FB
nav:
  - Home: index.md
  - Manual: manual.md
  - User Stories: user_stories.md
  - Design Document: design_document.md
  - System Test Document: system_test_document.md
  - Unit Test Report: surefire-report/surefire-report.html
markdown_extensions:
  - pymdownx.superfences
extra_css:
  - css/custom.css